const fs = require('fs');

let code = fs.readFileSync('src/pages/SalesPageES.tsx', 'utf8');

const dict = {
  'SalesPage': 'SalesPageES',
  'PARA AGÊNCIAS DE VIAGEM QUE QUEREM PARAR DE PARECER AMADORAS': 'PARA AGENCIAS DE VIAJES QUE QUIEREN DEJAR DE PARECER AMATEURS',
  'Tenha um feed profissional de': 'Ten un feed profesional de',
  'R$ 10k/mês': '$ 6k USD/mes',
  'e crie anúncios de viagens automáticos com Inteligência Artificial!': 'y crea anuncios de viajes automáticos con Inteligencia Artificial!',
  'A única plataforma do mercado de turismo que combina': 'La única plataforma del mercado de turismo que combina',
  'vídeos 4K': 'videos 4K',
  'artes editáveis no Canva': 'diseños editables en Canva',
  'com a revolucionária': 'con la revolucionaria',
  'Fábrica de Anúncios com I.A': 'Fábrica de Anuncios con IA',
  '— onde você digita a oferta e recebe o anúncio pronto, com preços, parcelas e o seu logo em 5 segundos.': '— donde escribes la oferta y recibes el anuncio listo, con precios, cuotas y tu logo en 5 segundos.',
  'A partir de R$ 16,41/mês.': 'A partir de $ 17 USD/mes.',
  'Quero começar agora — a partir de R$ 16,41/mês': 'Quiero empezar ahora — a partir de $ 17 USD/mes',
  'avaliações verificadas': 'evaluaciones verificadas',
  'Cancele quando quiser': 'Cancela cuando quieras',
  'Acesso em 2 min': 'Acceso en 2 min',
  'Garantia dupla': 'Garantía doble',
  'Sem fidelidade': 'Sin permanencia',
  'Suporte em português': 'Soporte en español',
  'VELOCIDADE MÁXIMA': 'VELOCIDAD MÁXIMA',
  'COMO A IA CRIA': 'CÓMO LA IA CREA',
  'SEU ANÚNCIO': 'TU ANUNCIO',
  'Zero complexidade. Só 3 cliques entre a oferta e o vídeo.': 'Cero complejidad. Solo 3 clics entre la oferta y el video.',
  'VOCÊ DIGITA': 'TÚ ESCRIBES',
  'Preço, destino, parcelas.': 'Precio, destino, cuotas.',
  'IA CONSTRÓI': 'LA IA CONSTRUYE',
  'Arte montada em 2 segundos.': 'Diseño montado en 2 segundos.',
  'PRONTO': 'LISTO',
  'Direto no seu celular com sua logo.': 'Directo en tu celular con tu logo.',
  'CONECTE-SE AO MUNDO': 'CONÉCTATE AL MUNDO',
  'VENDA DESTINOS DE TODO O MUNDO': 'VENDE DESTINOS DE TODO EL MUNDO',
  'Escale suas vendas com mídias de profissionais para os destinos mais cobiçados do mercado nacional e internacional.': 'Escala tus ventas con medios profesionales para los destinos más codiciados del mercado nacional e internacional.',
  'Quem está por trás disso': 'Quién está detrás de esto',
  '. Operei agência de viagens e fazendo marketing para outras agências de viagens por 10 anos, fechei mais de': '. Operé agencias de viajes y haciendo marketing para otras agencias por 10 años, cerré más de',
  'R$ 4 milhões em pacotes vendidos online': '$ 800 mil USD en paquetes vendidos online',
  'para minha agência e meus clientes, e construí o Canva Viagem porque eu mesmo precisava disso e não encontrava.': 'para mi agencia y mis clientes, y construí Canva Viajes porque yo mismo lo necesitaba y no lo encontraba.',
  'Me seguir no Instagram →': 'Seguirme en Instagram →',
  'Experiência': 'Experiencia',
  '10 anos operando com agências de viagens emissivas e receptivas': '10 años operando con agencias de viajes emisivas y receptivas',
  'Comunidade': 'Comunidad',
  '64 mil seguidores no Instagram @lucasferrari.pro': '64 mil seguidores en Instagram @lucasferrari.pro',
  'Pioneirismo': 'Pionerismo',
  '1ª plataforma de marketing completa para viagens e turismo do mundo!': '¡1ª plataforma de marketing completa para viajes y turismo del mundo!',
  'VOCÊ SE IDENTIFICA?': '¿TE IDENTIFICAS?',
  'Vender viagens ficou impossível com um perfil comum': 'Vender viajes se volvió imposible con un perfil común',
  'Se você se identifica com algum desses, continue lendo.': 'Si te identificas con alguno de estos, sigue leyendo.',
  'Instagram Fantasma': 'Instagram Fantasma',
  'Você posta uma vez por semana (com medo) e o engajamento é zero. Cliente passa direto para o concorrente.': 'Publicas una vez por semana (con miedo) y la interacción es cero. El cliente pasa directo a la competencia.',
  'Designer Entregou Lixo': 'Diseñador Entregó Basura',
  'Pagou R$ 500 nas artes bonitas mas não vende.': 'Pagaste $ 100 USD en diseños bonitos pero no venden.',
  'Viajante de alta renda Te Ignora': 'Viajero de altos ingresos Te Ignora',
  'Quem paga R$ 8.000 por pacote olha seu perfil 3 segundos e vai para o concorrente com perfil e site top.': 'Quien paga $ 2,000 USD por paquete mira tu perfil 3 segundos y se va a la competencia con perfil y sitio top.',
  'Não Fazer Nada Custa Mais': 'No Hacer Nada Cuesta Más',
  'Cada dia com perfil e site parado são viagens que seu concorrente fecha no lugar de você. O custo real de não agir é muito mais que 8k/mês em vendas que você não faz.': 'Cada día con perfil y sitio parado son viajes que tu competidor cierra en tu lugar. El costo real de no actuar es mucho más de $ 2k/mes en ventas que no haces.',
  'COMO FUNCIONA': 'CÓMO FUNCIONA',
  '3 passos. 5 minutos.': '3 pasos. 5 minutos.',
  'Post no ar.': 'Publicación en línea.',
  'ESCOLHE': 'ELIGE',
  '250+ vídeos 4K por destino. Maragogi, Caribe, Europa — atualizados toda semana.': '250+ videos 4K por destino. Caribe, Europa — actualizados cada semana.',
  'PERSONALIZA': 'PERSONALIZA',
  'Abre no Canva, troca o logo, ajusta a cor da marca. Em 2 minutos está pronto.': 'Abre en Canva, cambia el logo, ajusta el color de la marca. En 2 minutos está listo.',
  'POSTA': 'PUBLICA',
  'Calendário pronto + scripts de WhatsApp para converter o DM em pacote vendido.': 'Calendario listo + scripts de WhatsApp para convertir el DM en paquete vendido.',
  'RESULTADOS REAIS': 'RESULTADOS REALES',
  'Quem virou a chave em 30 dias': 'Quien cambió el juego en 30 días',
  'PROVA REAL INDISCUTÍVEL': 'PRUEBA REAL INDISCUTIBLE',
  'Resultados diretos no WhatsApp de quem usa': 'Resultados directos en WhatsApp de quienes usan',
  'COMPARATIVO HONESTO': 'COMPARATIVO HONESTO',
  'Veja onde seu dinheiro rende mais': 'Mira dónde rinde más tu dinero',
  'Não vamos te enganar comparando com agência de design de R$ 10.000. Olha as alternativas reais que você está considerando agora.': 'No te engañaremos comparando con agencias de diseño de $ 2,000 USD. Mira las alternativas reales que consideras ahora.',
  'Pack único Hotmart': 'Pack único Hotmart',
  'Designer freelancer': 'Diseñador freelancer',
  'MELHOR ESCOLHA': 'MEJOR ELECCIÓN',
  'Investimento': 'Inversión',
  'Conteúdo': 'Contenido',
  'Atualizações': 'Actualizaciones',
  'IAs e Scripts': 'IAs y Scripts',
  'Suporte': 'Soporte',
  'R$ 197 uma vez': '$ 118 USD una vez',
  'R$ 1.500 / mês': '$ 300 USD / mes',
  'A partir de R$ 197 / ano': 'Desde $ 118 USD / año',
  '150 reels fixos': '150 reels fijos',
  '4–8 entregas/mês': '4–8 entregas/mes',
  '250+ vídeos 4K + Sites de Vendas': '250+ videos 4K + Sitios de Ventas',
  '❌ Nenhuma': '❌ Ninguna',
  'Depende dele': 'Depende de él',
  '✅ Acesso vitalício à evolução': '✅ Acceso vitalicio a la evolución',
  '❌ Não tem': '❌ No tiene',
  '✅ 11 IAs + Fábrica de Anúncios': '✅ 11 IAs + Fábrica de Anuncios',
  'Só do produtor': 'Solo del productor',
  '1 freelancer': '1 freelancer',
  'WhatsApp VIP direto com o Lucas': 'WhatsApp VIP directo con Lucas',
  'OPORTUNIDADE ÚNICA': 'OPORTUNIDAD ÚNICA',
  'Não saia sem garantir o seu': 'No salgas sin asegurar tu',
  'Lote Promocional': 'Lote Promocional',
  'Escolha abaixo a melhor opção de acesso para a sua agência antes que o preço suba na próxima virada de lote:': 'Elige abajo la mejor opción de acceso para tu agencia antes de que suba el precio:',
  'Garantir Plano Elite (R$ 347/ano)': 'Asegurar Plan Elite ($ 208 USD/año)',
  'Garantir Plano Start (R$ 197/ano)': 'Asegurar Plan Start ($ 118 USD/año)',
  'Acesso em 2 min · Garantia tripla · Cancelamento simples': 'Acceso en 2 min · Garantía triple · Cancelación simple',
  'R$ 16,41/mês': '$ 17 USD/mes'
};

for (const [pt, es] of Object.entries(dict)) {
  code = code.split(pt).join(es);
}

// Write the translated code
fs.writeFileSync('src/pages/SalesPageES.tsx', code);
console.log('Translated SalesPageES!');
