const fs = require('fs');

const esPath = 'c:/Users/win 10/Desktop/CANVA_VIAGEM_ESTAVEL_24_ABRIL/src/pages/fabrica/Phase3ArtFactoryES.tsx';
const ptPath = 'c:/Users/win 10/Desktop/CANVA_VIAGEM_ESTAVEL_24_ABRIL/src/pages/fabrica/Phase3ArtFactory.tsx';
let code = fs.readFileSync(esPath, 'utf8');

// 1. Dicionário da Interface Geral
const dict = {
  'Vista Previa en Vivo': 'Visualização em Tempo Real',
  'Resultados Generados': 'Resultados Gerados',
  'Tu anuncio aparecerá aquí...': 'Seu anúncio aparecerá aqui...',
  'Llena los datos para ver la magia.': 'Preencha os dados para ver a mágica.',
  'Última generación': 'Última geração',
  'Avanzar a Fase 2 — Tu Sitio': 'Avançar para Fase 2 — Seu Site',
  'Generar Anuncio': 'Gerar Anúncio',
  'Descargar Todo (ZIP)': 'Baixar Tudo (ZIP)',
  'Descargar PNG': 'Baixar PNG',
  'Generando con IA...': 'Gerando com IA...',
  'Perfil y Canales de Atención': 'Perfil e Canais de Atendimento',
  'Modo de Creación y Categoría': 'Modo de Criação e Categoria',
  'Elegir una foto real': 'Escolher uma foto real',
  'Su imagen de referencia': 'Sua imagem de referência',
  'Datos del anuncio': 'Dados do anúncio',
  'Opciones Avanzadas (Colores y Textos)': 'Opções Avançadas (Cores e Textos)',
  'Identidad Visual': 'Identidade Visual',
  'Canales de Atención': 'Canais de Atendimento',
  'Modo de Creación': 'Modo de Criação',
  'Tipo de Anuncio': 'Tipo de Anúncio',
  'Formato del Anuncio': 'Formato do Anúncio',
  'Buscar destino (ej: Cancún, Orlando, Madrid...)': 'Buscar destino (ex: Cancún, Orlando, Paris...)',
  'Subir Logo': 'Subir Logo',
  'Archivo de Computadora': 'Arquivo do Computador',
  'Enlace de Internet (URL)': 'Link da Internet (URL)',
  'Elegir imagen de anuncio': 'Escolher imagem de anúncio',
  'Cambiar Logo': 'Trocar Logo',
  'Nombre del Destino': 'Nome do Destino',
  'Precio Base': 'Preço Base',
  'Moneda': 'Moeda',
  'Opción de Pago': 'Opção de Pagamento',
  'Sufijo del Precio (ej: por persona)': 'Sufixo do Preço (ex: por pessoa)',
  'Ocultar Centavos (,00)': 'Ocultar Centavos (,00)',
  'Mostrar Valor Total del Paquete': 'Mostrar Valor Total do Pacote',
  'Sobrescrever Valor Total (Opcional)': 'Sobrescrever Valor Total (Opcional)',
  'Mostrar Destacado Transferencia / Pix': 'Mostrar Faixa Desconto / Pix',
  'Familia de Fuentes': 'Família de Fontes',
  'Escala y Ajustes de Tamaño': 'Escala e Ajustes de Tamanho',
  'Generar Lote de Prueba A/B': 'Gerar Lote de Teste A/B',
  'Crea la página de ventas de tu agencia en el próximo paso': 'Crie a página de vendas da sua agência no próximo passo',
  'Proyectos Guardados': 'Projetos Salvos',
  'Contraer': 'Recolher',
  'Expandir / Cargar': 'Expandir / Carregar',
  'Seleccionar un proyecto...': 'Selecionar um projeto...',
  'No se encontraron proyectos guardados': 'Nenhum projeto salvo encontrado',
  'Nuevo': 'Novo',
  'Sin Nombre': 'Sem Nome',
  'Limpiar': 'Limpar',
  'Color de los textos base': 'Cor dos Textos Base',
  'Textos claros': 'Textos claros',
  'Textos oscuros': 'Textos escuros',
  'Color primario': 'Cor primária',
  'Color secundario': 'Cor secundária',
  'Fondo principal': 'Fundo principal',
  'Acento': 'Acento',
  'Restaurar': 'Restaurar',
  'beneficios.': 'benefícios.',
  'Color del texto': 'Cor do texto',
  'Versión del Layout': 'Versão do Layout',
  'Texto Integrado (Nueva)': 'Texto Integrado (Nova)',
  'Texto con fondo semi-transparente clásico': 'Texto com fundo semi-transparente clássico',
  'Diseño minimalista enfocado en la foto': 'Design minimalista focado na foto',
  'Mejor': 'Melhor',
  'Original': 'Original',
  'Sutil': 'Sutil',
  'Story / Reels': 'Story / Reels',
  'Cuadrado Feed': 'Quadrado Feed',
  'Ideal para Stories y Reels de Instagram': 'Ideal para Stories e Reels do Instagram',
  'Ideal para Feed y WhatsApp': 'Ideal para Feed e WhatsApp',
  'Ej: Cancún, Porto de Galinhas, Buenos Aires...': 'Ex: Cancún, Porto de Galinhas, Buenos Aires...',
  'Ej:': 'Ex:',
  'Campo Obligatorio': 'Campo Obrigatório',
  'Oferta de Paquete': 'Oferta de Pacote',
  'Foco en precio, cuotas, salidas e incluidos. Ideal para cerrar ventas rápidas.': 'Foco em preço, parcelas, saídas e inclusos. Ideal para fechar vendas rápidas.',
  'Experiencia de Destino': 'Experiência de Destino',
  'Foco visual, sentimento y exclusividad. Ideal para atraer leads cualificados.': 'Foco visual, sentimento e exclusividade. Ideal para atrair leads qualificados.',
  'Ventas': 'Vendas',
  'Lujo': 'Luxo',
  'Foto Real': 'Foto Real',
  'Tu Foto': 'Sua Foto',
  'Imagen IA': 'Imagem IA'
};

for (const [es, pt] of Object.entries(dict)) {
  code = code.split(es).join(pt);
}

// 2. Dicionário de Arrays e Defaults (Apenas PT puro)
const ptDefaults = {
  'Transporte incluido': 'Transporte incluso',
  'Alojamiento': 'Hospedagem',
  'Desayuno': 'Café da manhã',
  'Guía local': 'Guia local',
  'EXPERIENCIA SENSORIAL': 'EXPERIÊNCIA SENSORIAL',
  'MOMENTOS INOLVIDABLES': 'MOMENTOS INESQUECÍVEIS',
  'SELECCIÓN PREMIUM': 'CURADORIA PREMIUM',
  'por persona': 'por pessoa',
  'por pareja': 'por casal',
  'por paquete': 'por pacote',
  'por grupo': 'por grupo',
  'total del paquete': 'total do pacote',
  'Tu viaje empieza aquí': 'Sua viagem começa aqui',
  'Real (R$)': 'Real (R$)',
  'Dólar (US$)': 'Dólar (US$)',
  'Euro (€)': 'Euro (€)',
  'Libra (£)': 'Libra (£)',
  'Peso AR (AR$)': 'Peso AR (AR$)',
  'Cuotas': 'Parcelado',
  'Al contado': 'À vista',
  'Anticipo + cuotas': 'Entrada + parcelas',
  'Conoce lo mejor de {destino}': 'Conheça o melhor de {destino}',
  'Descubre {destino}': 'Descubra {destino}',
  'Paquete {destino}': 'Pacote {destino}',
  'Explora {destino}': 'Explore {destino}',
  '{destino} te sorprenderá': '{destino} vai te surpreender',
  '¡Tienes que conocer {destino}!': 'Você precisa conhecer {destino}!',
  'Qué hacer en {destino}': 'O que fazer em {destino}',
  'Lo mejor de {destino}': 'O melhor de {destino}',
  'Mi sueño se llama {destino}': 'Meu sonho se chama {destino}',
  'Nos vamos a {destino}': 'Partiu {destino}',
  'Tu próximo viaje es {destino}': 'Sua próxima viagem é {destino}',
  'Paquete Promocional {destino}': 'Pacote Promocional {destino}',
  'Viaje Completo {destino}': 'Viagem Completa {destino}',
  '{destino} te espera': '{destino} te espera',
  '¿Vamos a {destino}?': 'Vamos para {destino}?',
  'Vive lo mejor de {destino}': 'Viva o melhor de {destino}',
  'Momentos inolvidables en {destino}': 'Momentos inesquecíveis em {destino}',
  'Despierta tus sentidos en {destino}': 'Desperte os sentidos em {destino}',
  'Experiencia exclusiva en {destino}': 'Experiência exclusiva em {destino}',
  'Placer en cada detalle · {destino}': 'Prazer em cada detalhe · {destino}',
  '{destino} como nunca lo viviste': '{destino} como você nunca viveu',
  'All Inclusive · {destino}': 'All Inclusive · {destino}',
  'Refugio de ensueño en {destino}': 'Refúgio dos sonhos em {destino}',
  'Descubre el lado secreto de {destino}': 'Descubra o lado secreto de {destino}',
  'EXPERIENCIA EXCLUSIVA': 'EXPERIÊNCIA EXCLUSIVA',
  'PLACER EN CADA VIAJE': 'PRAZER EM CADA VIAGEM',
  'VIVENCIA PREMIUM': 'VIVÊNCIA PREMIUM',
  'REFUGIO DE ENSUEÑO': 'REFÚGIO DOS SONHOS',
  'OFERTA ESPECIAL': 'OFERTA ESPECIAL',
  'SÚPER OFERTA': 'SUPER OFERTA',
  'ÚLTIMOS LUGARES': 'ÚLTIMAS VAGAS',
  'PROMOCIÓN DEL DÍA': 'PROMOÇÃO DO DIA',
  'LIQUIDACIÓN': 'QUEIMA DE ESTOQUE',
  '5 días': '5 dias',
  '7 días': '7 dias',
  '10 días': '10 dias',
  '15 días': '15 dias',
  'Fin de semana': 'Final de semana',
  'Enero': 'Janeiro',
  'Julio': 'Julho',
  'Diciembre': 'Dezembro',
  'Fin de semana largo': 'Feriado prolongado',
  'Fecha flexible': 'Data flexível',
  'Salidas semanales': 'Saídas semanais'
};

for (const [es, pt] of Object.entries(ptDefaults)) {
  code = code.split(es).join(pt);
}

// 3. Substituir o export
code = code.replace(/export const Phase3ArtFactoryES/g, 'export const Phase3ArtFactory');
code = code.replace(/Phase3ArtFactoryES =/g, 'Phase3ArtFactory =');

// 4. Salvar
fs.writeFileSync(ptPath, code);
console.log('SUCCESS');
