// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdsjxasolxoclchyqdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZHNqeGFzb2x4b2NsY2h5cWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNTA1NTQsImV4cCI6MjA4NDYyNjU1NH0.3EEvDMLjGvcEQKOkB4rfrBzXrCGBnkXKNFT9oYV2H9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});